config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

	get 'welcome/index'

	resources :stories do
		resources :paths
	end
	
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/path.rb
class Path < ApplicationRecord
	attr_accessor :next_zero, :next_one
	belongs_to :story



end

app/models/story.rb
class Story < ApplicationRecord
	has_many :paths
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
	def show
		path_id = params[:id]
		story_id = params[:story_id]
		i = 0
		@paths = []
		while i < path_id.length do
			this_path = Path.find_by(path_id: path_id[0..i], story_id: story_id)
			if Path.all.any?{|path| path.path_id == this_path.path_id+"0" && path.story_id == this_path.story_id}
				this_path.next_zero = true
			else this_path.next_zero = false
			end
			if Path.all.any?{|path| path.path_id == this_path.path_id+"1" && path.story_id == this_path.story_id}
				this_path.next_one = true
			else this_path.next_one = false
			end
			@paths.append(this_path)
			i += 1
		end
		@path_id = path_id
	end

	def new
		@story = Story.find(params[:story_id])
	end

	def edit
		@story = Story.find(params[:story_id])
		@path = Path.find_by(path_id: params[:id], story_id: params[:story_id])
	end

	def update
		@path = Path.find_by(path_id: params[:id], story_id: params[:story_id])
    	@path.update_attributes(prompt: params[:path][:prompt], decision1: params[:path][:decision1], decision2: params[:path][:decision2])
    	redirect_to "/stories/#{@path.story_id}/paths/#{@path.path_id}"
  	end

	def create
		@story = Story.find(params[:story_id])
		@path = Path.new(prompt: params[:path][:prompt], decision1: params[:path][:decision1], decision2: params[:path][:decision2], path_id: params[:path_id], story_id: params[:story_id], ended: params[:ended])
		if params[:path][:ended] === "1"
			@path.ended = true
		elsif params[:path][:ended] === "0"
			@path.ended = false
		end
		@path.save
		redirect_to "/stories/#{@story.id}/paths/#{@path.path_id}"
	end

	private
		def path_params
			params.require(:path).permit(:prompt, :decision1, :decision2, :path_id, :story_id, :ended)
		end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	def index
		@stories = Story.all
	end

	def show
		@story = Story.find(params[:id])
		@paths = Path.where(story_id: params[:id])
		@path = Path.new
	end

	def new
	end

	def edit
		@story = Story.find(params[:id])
	end

	def update
    	@story = Story.find(params[:id])
    	@story.update_attributes(story_params)
    	redirect_to @story
  	end

	def create
		@story = Story.new(story_params)
		@story.save
		redirect_to @story
	end

	private
		def story_params
			params.require(:story).permit(:title)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choose Your Own</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class = "container">
      <div class = "header" style="margin-top: 10px">
        <div class = "row">
          <div class = "three columns">
            <%= button_to "See All stories", "/stories/", :method => :get %>
          </div>
          <div class = "six columns" style= "text-align: center">
            <h3 style="color: #33C3F0"><%= link_to "Choose Your Own", "/" %></h3>
          </div>
          <div class = "three columns" style="text-align: right">
            <%= button_to "Start a new story", "/stories/new", :method => :get %>
          </div>
        </div>
    	<%= yield %>
	   </div>
  </body>
</html>

app/views/paths/edit.html.erb
<div class = "header">
	<div class = "title">
		<%= @story.title %>
	</div>
</div>
<div class="eight columns offset-by-two" >
	<%= form_with scope: :path, url: "/stories/#{@path.story.id}/paths/#{@path.path_id}", :method => "patch", local: true do |form| %>
			<p>
			<%= form.label :prompt %><br>
			<%= form.text_area :prompt, :value => @path.prompt, class: "u-full-width prompt-area" %>
			</p>

			<p>
			<%= form.label :decision_1 %><br>
			<%= form.text_field :decision1, class: "u-full-width" %>
			</p>

			<p>
			<%= form.label :decision_2 %><br>
			<%= form.text_field :decision2, class: "u-full-width" %>
			</p>

			<%= hidden_field_tag :path_id, "0" %>
			<%= hidden_field_tag :ended, false %>

		<p>
			<%= form.submit %>
		</p>
	<% end %>
<div>

app/views/paths/new.html.erb
<div class = "header">
	<div class = "title">
		<%= @story.title %>
	</div>
</div>
<div class="eight columns offset-by-two" >
	<%= form_with scope: :path, url: story_paths_path, local: true do |form| %>
			<p>
			<%= form.label :prompt %><br>
			<%= form.text_area :prompt, class: "u-full-width prompt-area" %>
			</p>

			<p>
			<%= form.label :decision_1 %><br>
			<%= form.text_field :decision1, class: "u-full-width" %>
			</p>

			<p>
			<%= form.label :decision_2 %><br>
			<%= form.text_field :decision2, class: "u-full-width" %>
			</p>

			<%= hidden_field_tag :path_id, "0" %>
			<%= hidden_field_tag :ended, false %>

		<p>
			<%= form.submit %>
		</p>
	<% end %>
<div>

app/views/paths/show.html.erb
<div class = "header">
	<div class= "row">
		<div class = "title">
			<%= @paths.last.story.title %> <%= button_to 'Edit', edit_story_path(@paths.last.story), :method => :get %>
		</div>
	</div>
</div>
<% @paths.each do |path| %>
	<% if path.path_id == @path_id %>
		<div id="last_prompt">
	<% else %>
		<div>
	<% end %>
		<h2>
			<strong><%= path.prompt %></strong>
		</h2>
	</div>
	<%= button_to 'Edit', "/stories/#{path.story.id}/paths/#{path.path_id}/edit", :method => "get" %>
	<div class="row">
		<div class="five columns">
		<% unless path.ended %>
			<% unless path.next_zero %> 
				<div class="unfinished">
				<h3> <%= path.decision1 %> </h3>
				<p style="text-align: center">
					and then what happens next?
				</p>
				<%= form_with scope: :path, url: story_paths_path, local: true do |form| %>
					<p>
						<%= form.label :prompt %><br>
						<%= form.text_area :prompt, class: "u-full-width prompt-area" %>
					</p>

					<p>
						<%= form.label :decision_1 %><br>
						<%= form.text_field :decision1, class: "u-full-width" %>
					</p>
					
					<p>
						<%= form.label :decision_2 %><br>
						<%= form.text_field :decision2, class: "u-full-width" %>
					</p>

					<p>	
						<%= form.label 'End this path here?' %>
						<%= form.check_box :ended %>
					</p>

					<p>
						<%= hidden_field_tag :path_id, path.path_id+"0" %>
					</p>

					<p>
						<%= form.submit %>
					</p>
				</div>
				<% end %>
			<% else %>
				<% if path.path_id+"0" == @paths.last.path_id[0..path.path_id.length] %>
					<% button_type = "button-primary" %>
				<% else %>
					<% button_type = "" %>
				<% end %>
					<%= button_to path.decision1, path.path_id+"0", :method => "get", class: button_type %>	
			<% end %>
		</div>
		<div class="two columns" style="text-align: center; padding-top: 25px">or</div>
		<div class="five columns" style="text-align: right">
			<% unless path.next_one || path.ended %> 
				<div class="unfinished" style="text-align: left">
				<h3> <%= path.decision2 %> </h3>
				<p style="text-align: center">
					and then what happens next?
				</p>
				<%= form_with scope: :path, url: story_paths_path, local: true do |form| %>
					<p>
						<%= form.label :prompt %><br>
						<%= form.text_area :prompt, class: "u-full-width prompt-area" %>
					</p>

					<p>
						<%= form.label :decision_1 %><br>
						<%= form.text_field :decision1, class: "u-full-width" %>
					</p>
					
					<p>
						<%= form.label :decision_2 %><br>
						<%= form.text_field :decision2, class: "u-full-width" %>
					</p>

					<p>
						<%= hidden_field_tag :path_id, path.path_id+"1" %>
					</p>

					<p>	
						<%= form.label 'End this path here?' %>
						<%= form.check_box :ended %>
					</p>

					<p>
						<%= form.submit %>
					</p>
				</div>
				<% end %>
			<% else %>
				<% if path.path_id+"1" == @paths.last.path_id[0..path.path_id.length] %>
					<% button_type = "button-primary" %>
				<% else %>
					<% button_type = "" %>
				<% end %>
				<%= button_to path.decision2, path.path_id+"1", :method => "get", class: button_type %>

			<% end %>	
		<% end %>
		</div>
	</div>
<% end %>
<% if @paths.length != 1 %>
	<div style="text-align: center; margin-top: 10px;">
		<%= button_to "back to the start", "0", :method => "get" %> 
	</div>
<% end %>
<script>
	(function scrollToPrompt() {
		window.scrollTo(0, (document.getElementById("last_prompt").offsetTop))
	})()
</script>

app/views/stories/edit.html.erb
    <div class="six columns offset-by-three" style="padding-top: 20px;">
    	<%= form_with scope: :story, url: story_path(@story), :method => "patch", local: true do |form| %>
		<div style="text-align: center">
			<%= form.label :title %><br>
			<%= form.text_field :title, :value => @story.title, class: "u-full-width"%>
		</p>

		<p>
			<%= hidden_field_tag :story_id, @story.id %>
		</p>

		<p>
			<%= form.submit %>
		</p>
	<% end %>
	</div>

app/views/stories/index.html.erb
<div class = "header">
	<div class = "title">
		Checkout these stories
	</div>
</div>
<% @stories.each do |story| %>
<% if story.title == ""%>
	<% story.title = "untitled" %>
<% end %>

<div class="row">
	<div class="six columns">
		<%= button_to story.title, "/stories/#{story.id}/", :method => :get %>
	</div>
	<div class="six columns">
		This story has <%= story.paths.length %> different paths to go on!
	</div>
</div>
<% end %>

app/views/stories/new.html.erb
    <div class="six columns offset-by-three" style="padding-top: 20px;">
    	<%= form_with scope: :story, url: stories_path, local: true do |form| %>
		<div style="text-align: center">
			<%= form.label :title %><br>
			<%= form.text_field :title, class: "u-full-width"%>
		</p>


		<p>
			<%= form.submit %>
		</p>
	<% end %>
	</div>

app/views/stories/show.html.erb
<div class = "header">
	<div class = "title">
		<%= @story.title %>
	</div>
</div>
<div style="text-align: center">
<% if @paths.length === 0 %>
<p><%= button_to "Start a path", "/stories/#{@story.id}/paths/new", :method => :get %></p>

<% else %>
<p>
	<%= button_to "Start at the beginning", "/stories/#{@story.id}/paths/0", :method => :get, class: "button-primary" %>
</p>

<p> or Jump to a decision point</p>
</div>
<% end %>
<% @paths.each do |path| %>
	<% if path.prompt.length > 30 %>
		<% link_preview = path.prompt[0..30]+"..." %>
		<% else %>
		<% link_preview = path.prompt %>
		<% end %>

<p>
	<%= button_to link_preview, "/stories/#{@story.id}/paths/#{path.path_id}", :method => :get %>
</p>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
	<section class="header">
		<div class="row">
			<h1 class="title">Hello!</h1>
		</div>
		<div class="row" style="text-align: center; margin-top: 5%">
			<div class="six columns">
				<%= button_to "Checkout some stories!", "/stories", :method => :get %>
			</div>
			<div class="six columns">
				<%= button_to "Make a story!", "/stories/new", :method => :get %>
			</div>
		</div>
	</section>
</div>